# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EDTravelCompanion',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/EDTravelCompanion',
                'lib_path': 'EDTravelCompanion'},
  'syms': { 'EDTravelCompanion.core': {'EDTravelCompanion.core.foo': ('core.html#foo', 'EDTravelCompanion/core.py')},
            'EDTravelCompanion.edastro': { 'EDTravelCompanion.edastro.create_galaxymap_url': ( 'md/edastro.html#create_galaxymap_url',
                                                                                               'EDTravelCompanion/edastro.py'),
                                           'EDTravelCompanion.edastro.embed_galaxymap': ( 'md/edastro.html#embed_galaxymap',
                                                                                          'EDTravelCompanion/edastro.py')},
            'EDTravelCompanion.linalg.fitsvd': { 'EDTravelCompanion.linalg.fitsvd.fitline': ( 'linalg/linalg_fitsvd.html#fitline',
                                                                                              'EDTravelCompanion/linalg/fitsvd.py')},
            'EDTravelCompanion.md.edastro': { 'EDTravelCompanion.md.edastro.create_galaxymap_url': ( 'md/edastro.html#create_galaxymap_url',
                                                                                                     'EDTravelCompanion/md/edastro.py'),
                                              'EDTravelCompanion.md.edastro.embed_galaxymap': ( 'md/edastro.html#embed_galaxymap',
                                                                                                'EDTravelCompanion/md/edastro.py')}}}
