"""Fit a line with Singular Value Decomposition"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/linalg/10_linalg_fitsvd.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/linalg/10_linalg_fitsvd.ipynb 3
def foo(): 
    pass
