"""Cached Elite Dangerous systems data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_eddblocal.ipynb.

# %% auto 0
__all__ = ['SQLiteQueryParams', 'sqlite_query_params', 'SQLiteConnectionInterface', 'sqllite_connection_interface',
           'sqllite_connection', 'create_systems_table', 'create_systems_indices', 'remove_duplicates',
           'convert_systems_dumpfile_to_csv', 'convert_dumpfile_in_thread']

# %% ../../nbs/05_eddblocal.ipynb 5
import sys, logging, typing 
import os, csv, json, gzip, sqlite3
import subprocess, queue, threading

import pandas as pd

from typing import Any, NamedTuple
from contextlib import contextmanager
from ..core import configuration
from ..threadworkers import bind_queue_as_generator_blocking


# %% ../../nbs/05_eddblocal.ipynb 8
syslog = logging.getLogger(__name__)
eddb_config = configuration["EDDB"]
syslog.info(f"Loading module {__name__}, config={eddb_config}")


# %% ../../nbs/05_eddblocal.ipynb 11
class SQLiteQueryParams(NamedTuple):
    as_param: typing.Callable
    append_param: typing.Callable   
    get_params: typing.Callable  


# %% ../../nbs/05_eddblocal.ipynb 12
def sqlite_query_params(log=None) -> SQLiteQueryParams:
    sql_params = {}

    def as_param(name:str):
        return f":{str(name)}"
   
    def append_param(name:str, value:Any):
        assert str(name) not in sql_params, f"Duplicate parameter {name}"
        assert len(sql_params) < 32766, "SQLite does not allow more then approx. 32k bound parameters"

        last_name = str(name)
        sql_params[last_name] = value
        return as_param(last_name)
    
    def get_params():
        return sql_params.copy()
    
    return SQLiteQueryParams(
        as_param=as_param,
        append_param=append_param if log is None else lambda p: log(append_param(p)),
        get_params=get_params
    )

# %% ../../nbs/05_eddblocal.ipynb 14
class SQLiteConnectionInterface(typing.NamedTuple):
    cursor: typing.Callable
    commit: typing.Callable
    rollback: typing.Callable
    close: typing.Callable
    execute: typing.Callable
    executemany: typing.Callable


# %% ../../nbs/05_eddblocal.ipynb 16
def sqllite_connection_interface(
        database:str=":memory:",
    ) -> SQLiteConnectionInterface:

    vi = sys.version_info
    assert vi.major >= 3, f"Python >= 3.0 required. Found {vi.major}.{vi.minor}.{vi.micro}"

    if vi.minor > 11:   
        syslog.info("Using legacy autocommit")
        connection = sqlite3.connect(database, autocommit=sqlite3.LEGACY_TRANSACTION_CONTROL, isolation_level='DEFERRED')
    else:
        syslog.info("Using isolation_level=None")
        connection = sqlite3.connect(database, isolation_level=None)

    def close():
        syslog.info("Closing connection")
        connection.close()

    def commit():
        syslog.info("Committing on connection")
        connection.commit()

    def rollback():
        syslog.info("Rolling back connection")
        connection.rollback()
    
    def cursor():
        syslog.info("Creating cursor")
        return connection.cursor()
    
    def execute(sql:str, params:tuple|dict=()):
        return connection.execute(sql, params)
    
    def execute_many(sql:str, params:list[tuple|dict]=[]):
        return connection.executemany(sql, params)

    syslog.info("Returning connection-interface")
    return SQLiteConnectionInterface(
        cursor=cursor,
        commit=commit,
        rollback=rollback,
        close=close,
        execute=execute,
        executemany=execute_many
    )

# %% ../../nbs/05_eddblocal.ipynb 18
@contextmanager
def sqllite_connection(*args, **kwargs):
    syslog.info(f"Opening connection-interface to {args}")
    interface = sqllite_connection_interface(*args, **kwargs)
    try:
        yield interface
    finally:
        interface.close()

# %% ../../nbs/05_eddblocal.ipynb 25
def create_systems_table(systems_databasefile, tablename='systems'):

    with sqllite_connection(systems_databasefile) as conn:
        syslog.info(f"Dropping table {tablename} ...")
        conn.execute(f"""
                DROP TABLE IF EXISTS {tablename};
            """
        )

        syslog.info(f"Creating table {tablename} ...")
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS {tablename} (
                id64 BIGINT NOT NULL,
                x DOUBLE PRECISION  NOT NULL,
                y DOUBLE PRECISION  NOT NULL,
                z DOUBLE PRECISION  NOT NULL,
                name TEXT NOT NULL
            ); """
        )


# %% ../../nbs/05_eddblocal.ipynb 26
def create_systems_indices(systems_databasefile, tablename='systems'):

    syslog.info(f"Adding indexes to {tablename} ...")
    with sqllite_connection(systems_databasefile) as conn:
        for sql in f"""
            CREATE INDEX IF NOT EXISTS {tablename}_x_idx ON systems (x);
            CREATE INDEX IF NOT EXISTS {tablename}_y_idx ON systems (y);
            CREATE INDEX IF NOT EXISTS {tablename}_z_idx ON systems (z); 
            CREATE INDEX IF NOT EXISTS {tablename}_name_idx ON systems (name)
        """.split(";"):
            conn.execute(sql)


# %% ../../nbs/05_eddblocal.ipynb 27
def remove_duplicates(systems_databasefile, tablename='systems', column='id64'):

    with sqllite_connection(systems_databasefile) as conn:
        
        syslog.info("Removing duplicates by id")

        # create temporary index
        index_name = f"{tablename}_{column}_idx"
        conn.execute(f"CREATE INDEX IF NOT EXISTS {index_name} ON {tablename} ({column})")
        conn.execute(f"""
                DELETE FROM {tablename}
                WHERE rowid NOT IN (
                    SELECT MIN(rowid)
                    FROM {tablename}
                    GROUP BY {column}
                ); """
        )

        syslog.info(f"Adding unique index {index_name} on {tablename} {column} ...")

        conn.execute(f"DROP INDEX IF EXISTS {index_name}")
        conn.execute(f"CREATE UNIQUE INDEX IF NOT EXISTS {index_name} ON {tablename} ({column})")

# %% ../../nbs/05_eddblocal.ipynb 31
def convert_systems_dumpfile_to_csv(infile, chunksize=128*1024*1024 ):

    with gzip.open(infile, 'rt') as jsonfile:
        chunknr = 0

        while True:

            chunk = jsonfile.readlines(chunksize)
            if chunk:

                csv_filename = infile.replace('.json.gz', f'_{chunknr:05d}.csv')
                syslog.info(f"Writing {csv_filename}")

                with open(csv_filename, 'w', newline='') as csvfile:
                    fieldnames = ['id64', 'x', 'y', 'z', 'name']
                    writer = csv.writer(csvfile, delimiter=',',
                                            quotechar='|', quoting=csv.QUOTE_MINIMAL)

                    writer.writerow(fieldnames)

                    for line in chunk:
                        if len(line) > 4:
                            item = json.loads(line.rstrip(',\n\r '))
                            writer.writerow( [item.get('id64')]+list(item.get('coords').values())+[item.get('name')])
                

                chunknr += 1
                yield csv_filename

            else:
                break


# %% ../../nbs/05_eddblocal.ipynb 35
def convert_dumpfile_in_thread(infile, systems_databasefile, tablename):
    
    fn = queue.Queue()

    def csv_maker():
        for f in convert_systems_dumpfile_to_csv(infile, chunksize=256*1024*1024 ):
            syslog.info(f"Adding {f} to queue")
            fn.put_nowait(f)

        fn.put_nowait(None)
    
    thread_csv = threading.Thread(target=csv_maker)
    thread_csv.start()

    get_filenames = bind_queue_as_generator_blocking(fn)
    for csv_filename in get_filenames():
        if csv_filename is None:
            syslog.info("No more files in queue")
            break

        syslog.info(f"Received {csv_filename} for {tablename}")
        import_systems_csv_to_sqlite(systems_databasefile, csv_filename, tablename)
        os.remove(csv_filename)

    thread_csv.join()
    syslog.info("Done")
    


