# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_eddbreader.ipynb.

# %% auto 0
__all__ = ['dbfilereader', 'dbfile_process', 'dbfile_process_async']

# %% ../../nbs/04_eddbreader.ipynb 3
import sys, time, logging, json, gzip, os
import edcompanion.core

from pathlib import Path
from ..core import configuration


# %% ../../nbs/04_eddbreader.ipynb 6
syslog = logging.getLogger(__name__)
syslog.info(f"Loading module {__name__}")

# %% ../../nbs/04_eddbreader.ipynb 8
def dbfilereader(filename):
    """
        Opens 'filename' as generator for eddb style objects
    """

    chunksize = 64 * 1024 * 1024

    with gzip.open(filename, 'rt') as jsonfile:

        while True:
            chunk = jsonfile.readlines(chunksize)
            if chunk:
                for line in chunk:
                    if len(line) < 5:
                        continue

                    yield json.loads(line.rstrip(',\n\r '))

            else:
                break




# %% ../../nbs/04_eddbreader.ipynb 13
def dbfile_process(filename, process_chunk):
    """Opens file and calls process_chunk to process batches of items"""

    chunksize = 16 * 1024 * 1024

    with gzip.open(filename, 'rt') as jsonfile:

        while True:
            chunk = jsonfile.readlines(chunksize)
            if chunk:
                data = []
                for line in chunk:
                    if len(line) < 5:
                        continue

                    item = json.loads(line.rstrip(',\n\r '))
                    data.append(item)

                process_chunk(data)

            else:
                break



# %% ../../nbs/04_eddbreader.ipynb 14
async def dbfile_process_async(filename, process_chunk):
    """Opens file and calls process_chunk to process batches of items"""

    chunksize = 16 * 1024 * 1024

    with gzip.open(filename, 'rt') as jsonfile:

        while True:
            chunk = jsonfile.readlines(chunksize)
            if chunk:
                data = []
                for line in chunk:
                    if len(line) < 5:
                        continue

                    item = json.loads(line.rstrip(',\n\r '))
                    data.append(item)

                await process_chunk(data)

            else:
                break


