"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['configuration']

# %% ../nbs/00_core.ipynb 3
import os
import logging

from confproxy.ini import init_configuration, get_config_path, get_log_path
from confproxy.core import init_console_logging


# %% ../nbs/00_core.ipynb 5
syslog = logging.getLogger(__name__)


# %% ../nbs/00_core.ipynb 11
configuration = init_configuration(get_config_path('EDTravelCompanion'),  'settings.ini')
syslog.info(configuration)
