"""Threaded workers and their queues to isolate user-interfaces from IO operations and CPU intensive tasks into a background thread"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_threadworkers.ipynb.

# %% auto 0
__all__ = ['QueueGetArgs', 'QueuePutArgs', 'WorkerArgs', 'bind_task_queue_generator']

# %% ../nbs/02_threadworkers.ipynb 3
import threading
import queue
import time
import logging

from typing import NamedTuple, Callable, Any

from .core import configuration


# %% ../nbs/02_threadworkers.ipynb 6
syslog = logging.getLogger(__name__)


# %% ../nbs/02_threadworkers.ipynb 11
class QueueGetArgs(NamedTuple):
    block: bool
    timeout: float

def _create_queue_get_args(block, timeout):
    return QueueGetArgs(block=block, timeout=timeout)

class QueuePutArgs(NamedTuple):
    block: bool
    timeout: float

def _create_queue_put_args(block, timeout):
    return QueuePutArgs(block=block, timeout=timeout)

# %% ../nbs/02_threadworkers.ipynb 14
class WorkerArgs(NamedTuple):
    args: tuple
    kwargs: dict


# %% ../nbs/02_threadworkers.ipynb 16
def _bind_queue_put_nowait(
        task_queue,     # The queue to put work items into
) -> Callable[[WorkerArgs], None]:
    
    "Binds a queue with kwargs for putting work items non-blocking into the queue"

    def put_task_item(*work_args, **work_kwargs):
        task_queue.put_nowait(item=WorkerArgs(work_args, work_kwargs))

    return put_task_item



# %% ../nbs/02_threadworkers.ipynb 17
def _bind_queue_put(
        task_queue,     # The queue to put work items into
        block = True,   # Whether to block on full queue
        timeout = None, # Timeout for block
) -> Callable[[WorkerArgs], None]:
    
    "Binds a queue with kwargs for putting work items into the queue -defaults to blocking"

    def put_task_item(*work_args, **work_kwargs):
        task_queue.put(item=WorkerArgs(work_args, work_kwargs), block=block, timeout=timeout)

    return put_task_item


# %% ../nbs/02_threadworkers.ipynb 20
def _bind_queue_get(
        product_queue,      # The queue to get produced items from
        block = True,   # Whether to block on full queue
        timeout = None, # Timeout for block
) -> Callable[[], WorkerArgs]:
    
    "Binds a queue and kwargs for getting produced items from the queue"

    def get_task_item():
        try:
            item = product_queue.get(block=block, timeout=timeout)
            product_queue.task_done()

        except queue.Empty:
            item = None

        return item

    return get_task_item

# %% ../nbs/02_threadworkers.ipynb 21
def _bind_queue_get_nowait(
        product_queue,      # The queue to get produced items from
) -> Callable[[], WorkerArgs]:
    
    "Binds a queue and kwargs for getting produced items from the queue"

    def get_task_item():
        try:
            item = product_queue.get_nowait()
            product_queue.task_done()

        except queue.Empty:
            item = None

        return item

    return get_task_item

# %% ../nbs/02_threadworkers.ipynb 26
def bind_task_queue_generator(
        source_queue       # The queue to get produced items from
) -> callable:
    
    "Binds a queue for getting produced items from the queue"

    def get_task_items():
        try:
            while True:
                item = source_queue.get_nowait()
                source_queue.task_done()
                yield item

        except queue.Empty:
            pass

    return get_task_items

# %% ../nbs/02_threadworkers.ipynb 35
def _create_sleeper(base=0.1):

    class Sleeper(NamedTuple):
        sleep: Callable
        reset: Callable

    sleepfor = base
    sleepmax = 5*sleepfor

    def _sleep():
        time.sleep(sleepfor)
        sleepfor = min(sleepfor * 1.2, sleepmax)
        
    def _reset():
        sleepfor = 0.05

    return Sleeper(_sleep, _reset)


# %% ../nbs/02_threadworkers.ipynb 38
def workloop(
        task_queue: queue.Queue,
        product_queue: queue.Queue,
        worker_fn:  callable,
        stop_event: threading.Event,
    ):
        """
        A worker thread loop that gets items from a queue, processes 
        them with a worker function and puts it's result on a queue.
        """

        sleepfor = 0.05 # initial sleep time when no work is available
        sleepmax = 0.5  # max sleep time when no work is available

        def _sleep():
            time.sleep(sleepfor)
            sleepfor = min(sleepfor * 1.2, sleepmax)

        # indefinately keep getting new items from the queue to process
        while True:
            
            try:
                item = None
                try:
                    # by default queue.get() waits for new items
                    item = task_queue.get_nowait()
                    task_queue.task_done()
                    sleepfor = 0.05

                except queue.Empty:
                    if stop_event.is_set():
                        break
                    else:
                        _sleep()

                result = worker_fn(item)

                while True:
                    try:
                        product_queue.put_nowait(result)

                    except queue.Full:
                        if stop_event.is_set():
                            break
                        else:
                            _sleep()


            except Exception as x:
                syslog.exception("Exception: %s", x, exc_info=True, stack_info=True)


